### PR TITLE
Custom transitions

### PR DESCRIPTION
**Pull request by nicooprat**
Allow definition of custom transitions : https://github.com/PhilippSpo/momentum-flow-router/issues/11

### CODE REVIEW

**Comment by grundmanise** [comment]
Hi, @PhilippSpo . Can you please merge this commit?

**Comment by grundmanise** [comment]
@nicooprat tnx for your help. I also need custom transitions.

**Comment by nicooprat** [comment]
You're welcome ;)

**Comment by PhilippSpo** [comment]
👍

**Pull request merged**
